services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/code
    entrypoint: ./utils/app-entrypoint.sh
    command: uvicorn app.api.api:app --reload --host 0.0.0.0
  db:
    image: postgres:14.2-alpine3.15
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
