"""create_urls_table

Revision ID: a7cdd28d6f17
Revises:
Create Date: 2022-06-06 17:37:43.933465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a7cdd28d6f17"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "url",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("full_url", sa.String(), nullable=False),
        sa.Column("short_url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_url_short_url"), "url", ["short_url"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_url_short_url"), table_name="url")
    op.drop_table("url")
    # ### end Alembic commands ###
